name: ua-comparus

services:
  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-db
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql-db:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build: .
    image: user-service
    container_name: user-service
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB_URL=${POSTGRES_DB_URL}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - MYSQL_DB_URL=${MYSQL_URL}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  mysql_data:
